[package]
name = "rpc-to-prom"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0", features = ["full"] }
alloy-contract = "0"
alloy-pubsub = "0"
async-std = { version = "1.13.0", features = ["attributes", "tokio1"] }
dotenvy = "0.15.7"
poem = "3.1.5"
prometheus = "0.13.4"
reqwest = "0.12.9"
