[tokens.eth]
rpc_url = "https://eth.blockscout.com/api/eth-rpc"
wallets = [""]

[tokens.eth.usdc]
address = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
fixed_rate = 1.0

[tokens.eth.aaveusdc]
address = "0x98C23E9d8f34FEFb1B7BD6a91B7FF122F4e16F5c"
fixed_rate = 1.0

[tokens.eth.steth]
address = "0xae7ab96520de3a18e5e111b5eaab095312d7fe84"
# uniswap_v3 = ""

[tokens.eth.ens]
address = "0xc18360217d8f7ab5e7c516566761ea12ce7f9d72"
# uniswap_v2 = ""

[tokens.polygon]
rpc_url = "https://polygon.blockscout.com/api/eth-rpc"
wallets = [""]

[tokens.polygon.usdc]
address = "0x625e7708f30ca75bfd92586e17077590c60eb4cd"
fixed_rate = 1.0
