[chains.ethereum]
chain_id = 1
rpc_url = "https://reth-ethereum.ithaca.xyz/rpc"

[chains.ethereum.tokens.usdc]
address = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"

[chains.ethereum.tokens.aave_usdc]
address = "0x98C23E9d8f34FEFb1B7BD6a91B7FF122F4e16F5c"

[chains.ethereum.trackers.fixed.usdc]
token_in = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
token_out = "fiat:usdc"
fixed_rate = 1.0

[chains.ethereum.trackers.uniswap_v2.ens_usdc]
pair_address = "0xb169c3e8dda6456a18aefa49c58f7f53e120a9b4"

[chains.ethereum.trackers.uniswap_v2.weth_usdc]
token_in = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
token_out = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
